export const CACHE_ACTION_TYPES = Object.freeze({
  REPOSITORIES_REQUEST: 'REPOSITORIES_REQUEST',
  REPOSITORIES_REQUEST_SUCCESS: 'REPOSITORIES_REQUEST_SUCCESS',
  REPOSITORIES_REQUEST_FAILURE: 'REPOSITORIES_REQUEST_FAILURE',
  COMMITS_REQUEST: 'COMMITS_REQUEST',
  COMMITS_REQUEST_SUCCESS: 'COMMITS_REQUEST_SUCCESS',
  COMMITS_REQUEST_FAILURE: 'COMMITS_REQUEST_FAILURE',
});
